// Draw the import graph. GENERATED — never hand-edit `docs/architecture-graph.md`.
//
// The same instinct as `make-icons.mjs`: a picture of the current shape is exactly the kind
// of thing that rots the moment someone adds a module, so it is derived rather than drawn.
// README's diagram stays hand-written and stays a PIPELINE view — what flows where, which is
// an argument about design and doesn't rot. This is the complementary fact: which module
// actually imports which, today, straight from the source.
//
// Resolution comes from the same `.dependency-cruiser.cjs` that `npm run deps` enforces with,
// so the drawing and the check can never disagree about what depends on what.
//
// Mermaid rather than SVG on purpose: GitHub renders it inline, it diffs as text (so a review
// SEES an edge appear), and it needs no Graphviz on anyone's machine.

import {execFileSync} from 'node:child_process';
import {mkdirSync, writeFileSync} from 'node:fs';

const OUT = 'docs/architecture-graph.md';

/**
 * Test files and their fixtures are real modules but not part of the design being drawn.
 *
 * `importgraph.ts` is excluded for a sharper reason than "it's test support": it is the
 * fitness tests' own reader of this very graph, so drawing it inside the graph puts the
 * measuring instrument in the picture it measures. Left in, it renders as an isolated box —
 * every one of its dependents is an excluded test file — which reads as dead code in the one
 * artifact whose whole job is to show what's wired to what. `npm run deps` still cruises it
 * unexcluded, so `no-orphans` covers it there, where the answer is true.
 */
const EXCLUDE = '\\.test\\.ts$|testfixtures|src/importgraph\\.ts$';

function cruise(outputType) {
  return execFileSync(
    'npx',
    ['depcruise', 'src/**/*.ts', '--config', '.dependency-cruiser.cjs', '--exclude', EXCLUDE, '--output-type', outputType],
    {encoding: 'utf8', maxBuffer: 32 * 1024 * 1024},
  );
}

const mermaid = cruise('mermaid').trim();
const {modules} = JSON.parse(cruise('json'));
const edges = modules.reduce((n, m) => n + m.dependencies.length, 0);

// A graph that resolved nothing still renders — it just comes back as a pile of unconnected
// boxes. That is the failure mode of the resolver shim (see scripts/lib/ts-esm-resolve.cjs),
// and it is silent, so refuse to write one rather than publish a lie about the architecture.
if (edges < modules.length) {
  console.error(`✗ only ${edges} edges across ${modules.length} modules — resolution is broken, not writing ${OUT}`);
  process.exit(1);
}

mkdirSync('docs', {recursive: true});
writeFileSync(
  OUT,
  `# Module graph

<!-- GENERATED by \`npm run graph\` — do not edit. -->

Which module imports which, derived from the source. ${modules.length} modules, ${edges} edges.

This is the *current shape*. For what the layers MEAN — why \`facts.ts\` is a leaf, why every
deduction routes through \`narrow.ts\` — read the Architecture section of \`CLAUDE.md\`; for the
pipeline the data flows along, the diagram in \`README.md\`. Those are arguments and they don't
rot. This one does, which is why it is regenerated rather than maintained.

The rules that FAIL a build are elsewhere and are not restated here: the project's own layering
invariants live in \`src/dependency-boundaries.test.ts\` (run by \`npm run check\`), and the
structural ones — no cycles, no orphans — in \`.dependency-cruiser.cjs\` (run by \`npm run deps\`).

\`\`\`mermaid
${mermaid}
\`\`\`
`,
);

console.log(`✓ ${modules.length} modules, ${edges} edges → ${OUT}`);
